#ifndef BITBULLY_VERSION_H
#define BITBULLY_VERSION_H

#define PROJECT_VERSION ""
#define PROJECT_MAJOR_VERSION 
#define PROJECT_MINOR_VERSION 
#define PROJECT_PATCH_VERSION 

#endif  // BITBULLY_VERSION_H
