// Opening Book and transposition table could be the same table?
// TODO: use project-own google tests!!! Use git sub module!!!
// TODO: Simple neural net for move ordering? input board, output: 7-dim vector
// TODO: Use a simple logger. Use glog of google...
// TODO: Log computation times using a software version into a txt file...
// TODO: Play n games against a random (or more advanced) player: It has to win
// every single game! ...
// TODO: Github CI/CD Pipeline
// TODO: Namespace for Pons/FierzC4??

#include "Board.h"
#include "Solver.hpp"
#include "gtest/gtest.h"

class BoardTest : public ::testing::Test {

protected:
  void SetUp() override {}

  void TearDown() override {}

  ~BoardTest() override {
    // resources cleanup, no exceptions allowed
  }
};

TEST_F(BoardTest, canWin) {
  using B = BitBully::Board;
  using time_point =
      std::chrono::time_point<std::chrono::high_resolution_clock>;
  using duration = std::chrono::duration<float>;
  float time1 = 0.0F, time2 = 0.0F;
  uint64_t counter = UINT64_C(0);
  for (auto i = 0; i < 50000000; i++) {
    B b;
    GameSolver::Connect4::Position P;
    for (auto j = 0; j < 42; ++j) { // TODO: We need a random board generator...
      time_point tstart = std::chrono::high_resolution_clock::now();
      auto result1 = P.canWinNext();
      time_point tend = std::chrono::high_resolution_clock::now();
      float d = float(duration(tend - tstart).count());
      time1 += d;

      tstart = std::chrono::high_resolution_clock::now();
      auto result2 = b.canWin();
      tend = std::chrono::high_resolution_clock::now();
      d = float(duration(tend - tstart).count());
      time2 += d;

      ASSERT_EQ(result1, result2);
      counter++;
      int randColumn = rand() % 7;
      while (!P.canPlay(randColumn))
        randColumn = rand() % 7;

      ASSERT_TRUE(b.playMove(randColumn));
      P.playCol(randColumn);

      if (P.isWinningMove(randColumn)) {
        break;
      }
    }
  }

  std::cout << "Time Pons: " << time1 << ". Time Mine: " << time2 << std::endl;
  std::cout << "Pos./s Pons: " << static_cast<double>(counter) / time1
            << ". Pos./s Mine: " << static_cast<double>(counter) / time2
            << std::endl;
}

TEST_F(BoardTest, toString) {
  using B = BitBully::Board;
  B b, bb;
  B::TBoardArray arr;

  /* Generated by: genSetBoard */
  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};

  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 1);

  std::cout << b.toString();

  arr = {{{1, 1, 1, 2, 0, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {1, 2, 2, 1, 0, 0}, //
          {2, 1, 2, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {2, 2, 2, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);
  std::cout << b.toString();
}

TEST_F(BoardTest, setBoard1) { ASSERT_TRUE(false); }

TEST_F(BoardTest, setBoard2) { ASSERT_TRUE(false); }

TEST_F(BoardTest, setBoardX) { ASSERT_TRUE(false); }

TEST_F(BoardTest, toArray) {
  using B = BitBully::Board;

  /* Generated by: genSetBoard */
  B b, bb;
  B::TBoardArray arr{{{2, 0, 0, 0, 0, 0}, //
                      {1, 0, 0, 0, 0, 0}, //
                      {0, 0, 0, 0, 0, 0}, //
                      {1, 0, 0, 0, 0, 0}, //
                      {0, 0, 0, 0, 0, 0}, //
                      {2, 0, 0, 0, 0, 0}, //
                      {2, 1, 1, 2, 0, 0}}};

  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  /* Generated by: genSetBoard */
  arr = {{{1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 1}, //
          {1, 2, 1, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 1, 2, 2, 1, 0}, //
          {2, 2, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 2, 1, 2, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 1, 0, 0}, //
          {2, 2, 1, 2, 0, 0}, //
          {1, 1, 1, 2, 2, 0}, //
          {2, 1, 2, 1, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {1, 2, 2, 2, 1, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 1, 2, 2, 1}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 2, 0, 0}, //
          {1, 1, 2, 1, 1, 2}, //
          {1, 1, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {1, 1, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {1, 1, 1, 2, 2, 2}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 2, 1}, //
          {2, 2, 2, 0, 0, 0}, //
          {1, 1, 2, 1, 2, 1}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 2, 1, 2, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{0, 0, 0, 0, 0, 0}, //
          {1, 1, 1, 2, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 2, 2, 1, 0, 0}, //
          {1, 2, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 2, 0}, //
          {1, 1, 1, 2, 2, 1}, //
          {2, 1, 2, 1, 1, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 1, 1}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 2}, //
          {1, 1, 2, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 2, 2, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 2, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {2, 1, 2, 2, 0, 0}, //
          {1, 2, 1, 2, 2, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {2, 1, 1, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 2}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 2}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 2, 1, 1, 2, 1}, //
          {2, 1, 1, 2, 2, 1}, //
          {1, 2, 1, 2, 1, 2}, //
          {1, 2, 2, 2, 1, 2}, //
          {2, 1, 1, 1, 2, 1}, //
          {1, 2, 2, 2, 1, 1}, //
          {2, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 2, 2, 1, 2, 2}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 2, 1, 1, 2}, //
          {2, 1, 2, 1, 2, 1}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 1, 2, 1, 1}, //
          {2, 1, 1, 2, 1, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 2, 1, 1, 2, 2}, //
          {2, 1, 2, 2, 1, 0}, //
          {1, 2, 1, 1, 2, 1}, //
          {2, 1, 1, 2, 1, 2}, //
          {1, 2, 2, 1, 1, 1}, //
          {2, 1, 2, 1, 1, 2}, //
          {2, 2, 1, 1, 2, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 0}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
}

TEST_F(BoardTest, toArray2) {
  using B = BitBully::Board;
  B b, bb;
  B::TBoardArray arr;

  /* Generated by: genSetBoard */
  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 1);
  arr = {{{1, 2, 1, 1, 2, 2}, //
          {2, 1, 2, 2, 1, 0}, //
          {1, 2, 1, 1, 2, 1}, //
          {2, 1, 1, 2, 1, 2}, //
          {1, 2, 2, 1, 1, 1}, //
          {2, 1, 2, 1, 1, 2}, //
          {2, 2, 1, 1, 2, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 1);
  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 0}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 1);

  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 2}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 0);
  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 2}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 0);

  arr = {{{2, 2, 1, 2, 1, 0}, //
          {1, 2, 2, 1, 2, 1}, //
          {1, 1, 2, 2, 2, 1}, //
          {1, 2, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 0}, //
          {1, 1, 2, 1, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);
  arr = {{{2, 1, 1, 2, 0, 0}, //
          {1, 1, 2, 2, 0, 0}, //
          {2, 1, 2, 2, 1, 1}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {1, 1, 2, 2, 1, 2}, //
          {2, 2, 1, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);
  arr = {{{2, 2, 1, 1, 0, 0}, //
          {1, 2, 1, 2, 2, 1}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 1, 2, 2, 1, 2}, //
          {2, 2, 1, 1, 2, 2}, //
          {1, 1, 1, 2, 1, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);
  arr = {{{1, 1, 1, 2, 0, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {1, 2, 2, 1, 0, 0}, //
          {2, 1, 2, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {2, 2, 2, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);
  arr = {{{2, 1, 2, 2, 1, 1}, //
          {2, 2, 1, 0, 0, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {1, 2, 1, 1, 0, 0}, //
          {1, 2, 1, 2, 1, 1}, //
          {1, 2, 1, 2, 1, 0}, //
          {2, 1, 2, 2, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 11);

  arr = {{{2, 2, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 30);
  arr = {{{2, 2, 0, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 30);
  arr = {{{2, 2, 1, 2, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 30);
  arr = {{{1, 2, 1, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 30);

  /* Generated by: genSetBoard */
  arr = {{{0, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 41);
  arr = {{{0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 41);
  arr = {{{0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 41);

  arr = {{{0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 42);

  arr = {{{1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 1}, //
          {1, 2, 1, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 1, 2, 2, 1, 0}, //
          {2, 2, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 16);
  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 29);
  arr = {{{1, 1, 2, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 26);
  arr = {{{2, 2, 1, 2, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 25);
  arr = {{{2, 1, 1, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
  ASSERT_EQ(b.movesLeft(), 26);
}