// Opening Book and transposition table could be the same table?
// TODO: use project-own google tests!!! Use git sub module!!!
// TODO: Simple neural net for move ordering? input board, output: 7-dim vector
// TODO: Use a simple logger. Use glog of google...
// TODO: Log computation times using a software version into a txt file...
// TODO: Play n games against a random (or more advanced) player: It has to win
// every single game! ...
// TODO: Github CI/CD Pipeline
// TODO: Namespace for Pons/FierzC4??

#include "Board.h"
#include "Solver.hpp"
#include "gtest/gtest.h"

class BoardTest : public ::testing::Test {

protected:
  void SetUp() override {}

  void TearDown() override {}

  ~BoardTest() override {
    // resources cleanup, no exceptions allowed
  }
};

TEST_F(BoardTest, hasWin) {
  using B = BitBully::Board;
  using time_point =
      std::chrono::time_point<std::chrono::high_resolution_clock>;
  using duration = std::chrono::duration<float>;
  float time1 = 0.0F, time2 = 0.0F;
  for (auto i = 0; i < 1000000; i++) {

    B b;
    GameSolver::Connect4::Position P;
    for (auto j = 0; j < 42; ++j) { // TODO: We need a random board generator...
      time_point tstart = std::chrono::high_resolution_clock::now();
      auto result1 = P.canWinNext();
      time_point tend = std::chrono::high_resolution_clock::now();
      float d = float(duration(tend - tstart).count());
      time1 += d;

      tstart = std::chrono::high_resolution_clock::now();
      auto result2 = b.hasWin();
      tend = std::chrono::high_resolution_clock::now();
      d = float(duration(tend - tstart).count());
      time2 += d;

      ASSERT_EQ(result1, result2);
      int randColumn = rand() % 7;
      while (!P.canPlay(randColumn))
        randColumn = rand() % 7;

      if (P.isWinningMove(randColumn)) {
        break;
      }

      ASSERT_TRUE(b.playMove(randColumn));
      P.playCol(randColumn);
    }
  }

  std::cout << "Time Pons: " << time1 << ". Time Mine: " << time2 << std::endl;
}

TEST_F(BoardTest, setBoard1) { ASSERT_TRUE(false); }

TEST_F(BoardTest, setBoard2) { ASSERT_TRUE(false); }

TEST_F(BoardTest, setBoardX) { ASSERT_TRUE(false); }

TEST_F(BoardTest, toArray) {
  using B = BitBully::Board;

  /* Generated by: genSetBoard */
  B b, bb;
  B::TBoardArray arr{{{2, 0, 0, 0, 0, 0}, //
                      {1, 0, 0, 0, 0, 0}, //
                      {0, 0, 0, 0, 0, 0}, //
                      {1, 0, 0, 0, 0, 0}, //
                      {0, 0, 0, 0, 0, 0}, //
                      {2, 0, 0, 0, 0, 0}, //
                      {2, 1, 1, 2, 0, 0}}};

  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  /* Generated by: genSetBoard */
  arr = {{{1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 1}, //
          {1, 2, 1, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 1, 2, 2, 1, 0}, //
          {2, 2, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 2, 2, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 2, 1, 2, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 1, 0, 0}, //
          {2, 2, 1, 2, 0, 0}, //
          {1, 1, 1, 2, 2, 0}, //
          {2, 1, 2, 1, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 1, 0, 0, 0}, //
          {1, 2, 2, 2, 1, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 1, 2, 2, 1}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 2, 0, 0}, //
          {1, 1, 2, 1, 1, 2}, //
          {1, 1, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {1, 1, 2, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {2, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {1, 1, 1, 2, 2, 2}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 2, 1}, //
          {2, 2, 2, 0, 0, 0}, //
          {1, 1, 2, 1, 2, 1}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 2, 1, 2, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {2, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{0, 0, 0, 0, 0, 0}, //
          {1, 1, 1, 2, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {0, 0, 0, 0, 0, 0}, //
          {2, 1, 1, 0, 0, 0}, //
          {2, 2, 2, 1, 0, 0}, //
          {1, 2, 0, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 0, 0, 0, 0, 0}, //
          {2, 1, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 2, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 0, 0, 0, 0}, //
          {2, 2, 1, 1, 0, 0}, //
          {1, 2, 2, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 2, 0}, //
          {1, 1, 1, 2, 2, 1}, //
          {2, 1, 2, 1, 1, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 0, 0, 0, 0}, //
          {1, 2, 2, 1, 1, 1}, //
          {2, 0, 0, 0, 0, 0}, //
          {2, 1, 2, 2, 1, 2}, //
          {1, 1, 2, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 2, 1, 2, 2, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 0, 0, 0, 0, 0}, //
          {2, 2, 1, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {1, 0, 0, 0, 0, 0}, //
          {2, 0, 0, 0, 0, 0}, //
          {1, 2, 1, 1, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 1, 2, 2, 0, 0}, //
          {1, 1, 0, 0, 0, 0}, //
          {1, 2, 0, 0, 0, 0}, //
          {2, 1, 2, 2, 0, 0}, //
          {1, 2, 1, 2, 2, 0}, //
          {1, 2, 1, 2, 0, 0}, //
          {2, 1, 1, 0, 0, 0}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 2}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 2}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 2, 1, 1, 2, 1}, //
          {2, 1, 1, 2, 2, 1}, //
          {1, 2, 1, 2, 1, 2}, //
          {1, 2, 2, 2, 1, 2}, //
          {2, 1, 1, 1, 2, 1}, //
          {1, 2, 2, 2, 1, 1}, //
          {2, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 2, 2, 1, 2, 2}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 2, 1, 1, 2}, //
          {2, 1, 2, 1, 2, 1}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 1, 2, 1, 1}, //
          {2, 1, 1, 2, 1, 1}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 2, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 1}, //
          {1, 2, 2, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 2}, //
          {1, 2, 2, 1, 1, 0}, //
          {2, 1, 1, 2, 2, 1}, //
          {2, 1, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{1, 2, 1, 1, 2, 2}, //
          {2, 1, 2, 2, 1, 0}, //
          {1, 2, 1, 1, 2, 1}, //
          {2, 1, 1, 2, 1, 2}, //
          {1, 2, 2, 1, 1, 1}, //
          {2, 1, 2, 1, 1, 2}, //
          {2, 2, 1, 1, 2, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);

  arr = {{{2, 1, 1, 1, 2, 1}, //
          {1, 1, 1, 2, 1, 2}, //
          {2, 2, 1, 1, 1, 2}, //
          {1, 1, 2, 1, 2, 1}, //
          {2, 2, 2, 1, 2, 2}, //
          {2, 1, 1, 2, 2, 0}, //
          {1, 2, 1, 2, 1, 2}}};
  ASSERT_TRUE(b.setBoard(arr));
  ASSERT_EQ(b.toArray(), arr);
}

TEST_F(BoardTest, getColumnHeights) {
  using B = BitBully::Board;
  B::TBitBoard xYellow, xRed;
  B::THeightsArray expHeight;

  /* Generated by: genGetColumnHeights */
  xYellow = UINT64_C(0x20000000824);
  xRed = UINT64_C(0x800800018);
  expHeight = {1, 1, 0, 1, 0, 1, 4};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x230C00);
  xRed = UINT64_C(0x800C08200);
  expHeight = {0, 1, 0, 3, 3, 3, 0};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x10C00630000);
  xRed = UINT64_C(0x2020090C800);
  expHeight = {2, 3, 0, 4, 4, 1, 0};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x30C08020020);
  xRed = UINT64_C(0xC030C00800);
  expHeight = {4, 2, 3, 2, 1, 1, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x8C20020814);
  xRed = UINT64_C(0x3400081002A);
  expHeight = {4, 2, 1, 1, 2, 1, 5};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x8970810828);
  xRed = UINT64_C(0x3468C020410);
  expHeight = {4, 6, 4, 1, 2, 2, 3};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x20130018C28);
  xRed = UINT64_C(0x1CE00024210);
  expHeight = {4, 4, 2, 0, 4, 3, 3};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x20038000400);
  xRed = UINT64_C(0x4820A00);
  expHeight = {1, 0, 4, 1, 1, 3, 0};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x28C00A20500);
  xRed = UINT64_C(0x10030410A30);
  expHeight = {3, 2, 2, 3, 2, 4, 2};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x20000400C00);
  xRed = UINT64_C(0x20800220);
  expHeight = {1, 0, 1, 2, 0, 3, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x500D00C33);
  xRed = UINT64_C(0x30A2023800C);
  expHeight = {2, 4, 1, 4, 3, 2, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x800600A00);
  xRed = UINT64_C(0x400820420);
  expHeight = {0, 2, 0, 3, 1, 3, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x30230C20);
  xRed = UINT64_C(0x20C00C0E000);
  expHeight = {1, 2, 2, 3, 5, 2, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0xC20200430);
  xRed = UINT64_C(0x20200D20800);
  expHeight = {1, 3, 1, 4, 1, 2, 2};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x800620020);
  xRed = UINT64_C(0x420900010);
  expHeight = {0, 2, 1, 4, 1, 0, 2};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x8C28600334);
  xRed = UINT64_C(0x30310920C0A);
  expHeight = {3, 4, 3, 4, 1, 4, 5};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x10820810C00);
  xRed = UINT64_C(0x20010620220);
  expHeight = {2, 1, 2, 3, 2, 3, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x3AA2457B005);
  xRed = UINT64_C(0x55D8A84C3A);
  expHeight = {6, 6, 4, 6, 6, 2, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x13210B2BA93);
  xRed = UINT64_C(0x2CD284D452C);
  expHeight = {6, 4, 3, 6, 6, 5, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x106E6D26618);
  xRed = UINT64_C(0x2E9192D89A0);
  expHeight = {5, 6, 6, 6, 5, 5, 3};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x18E8ED0462A);
  xRed = UINT64_C(0x201712BB915);
  expHeight = {3, 6, 6, 5, 6, 4, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x116E6D2665A);
  xRed = UINT64_C(0x2E9192D99A5);
  expHeight = {6, 6, 6, 6, 6, 6, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x1DE8ED4462A);
  xRed = UINT64_C(0x221712BB9D5);
  expHeight = {6, 6, 6, 6, 6, 6, 6};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x30213A30C80);
  xRed = UINT64_C(0xC2C580330);
  expHeight = {2, 3, 6, 5, 2, 5, 2};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x3468C420A10);
  xRed = UINT64_C(0xA970818428);
  expHeight = {5, 6, 4, 2, 3, 3, 3};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));

  xYellow = UINT64_C(0x2003B920260);
  xRed = UINT64_C(0x18C04680D80);
  expHeight = {3, 2, 6, 5, 1, 6, 1};
  EXPECT_EQ(expHeight, B::getColumnHeights(xYellow, xRed));
}